name: Run JSON Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  json-server:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install JSON Server
      - name: Install JSON Server
        run: npm install -g json-server

      # Start JSON Server
      - name: Start JSON Server
        run: json-server --watch data.json --port 3000
        
      # Define the real API URL as an environment variable
      - name: Set Real API URL
        run: echo "API_BASE_URL=https://unixecureJsonServer.com" >> $GITHUB_ENV

      # Use the real URL to make a GET request
      - name: Fetch data from the real API using curl
        run: curl $API_BASE_URL/posts
